### ISSUE TITLE
[Issue] - Health Checker null-valued expression in Get-NicPnpCapabilitiesSetting

### ISSUE THREAD

**Issue by dpaulson45** [microsoft/CSS-Exchange#1300]
**Provide Version Number**
22.10.12.1839

**Describe the issue**
Script is failing to complete due to an exception: `You cannot call a method on a null-valued expression. `

**Expected behavior**
The script should be able to continue and handle the unexpected results of not being able to open the registry to check for Nic PNP Capabilities. 

**Script Output**

```
Error Index: 0
 : You cannot call a method on a null-valued expression.
Inner Exception:    at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
   at System.Management.Automation.PSScriptCmdlet.RunClause(Action`1 clause, Object dollarUnderbar, Object inputToProcess)
   at System.Management.Automation.PSScriptCmdlet.DoProcessRecord()
   at System.Management.Automation.CommandProcessor.ProcessRecord()
Script Stack: at Get-NicPnpCapabilitiesSetting<Process>, C:\Temp\HealthChecker.ps1: line 9090
at Get-NicInformation<Process>, C:\Temp\HealthChecker.ps1: line 9275
at Get-AllNicInformation<Process>, C:\Temp\HealthChecker.ps1: line 9400
at Get-OperatingSystemInformation, C:\Temp\HealthChecker.ps1: line 9892
at Get-HealthCheckerExchangeServer, C:\Temp\HealthChecker.ps1: line 10089
at Main, C:\Temp\HealthChecker.ps1: line 12229
at <ScriptBlock>, C:\Temp\HealthChecker.ps1: line 12262
at <ScriptBlock>, <No file>: line 1
at <ScriptBlock><End>, c:\users\userA\server.fqdn.psm1at.psm1: line 15761
at <ScriptBlock>, <No file>: line 1
-----------------------------------


Error Index: 1
 : Exception calling "OpenRemoteBaseKey" with "2" argument(s): "The network path was not found.
"
Inner Exception:    at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at Get-RemoteRegistrySubKey<Process>(Closure , FunctionContext )
Script Stack: at Get-RemoteRegistrySubKey<Process>, C:\Temp\HealthChecker.ps1: line 7210
at Get-NicPnpCapabilitiesSetting<Process>, C:\Temp\HealthChecker.ps1: line 9088
at Get-NicInformation<Process>, C:\Temp\HealthChecker.ps1: line 9275
at Get-AllNicInformation<Process>, C:\Temp\HealthChecker.ps1: line 9400
at Get-OperatingSystemInformation, C:\Temp\HealthChecker.ps1: line 9892
at Get-HealthCheckerExchangeServer, C:\Temp\HealthChecker.ps1: line 10089
at Main, C:\Temp\HealthChecker.ps1: line 12229
at <ScriptBlock>, C:\Temp\HealthChecker.ps1: line 12262
at <ScriptBlock>, <No file>: line 1
at <ScriptBlock><End>, c:\users\userA\server.fqdn.psm1at.psm1: line 15761
at <ScriptBlock>, <No file>: line 1
-----------------------------------


Error Index: 2
 : Exception calling "OpenRemoteBaseKey" with "2" argument(s): "The network path was not found.
"
Inner Exception:    at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at Get-RemoteRegistrySubKey<Process>(Closure , FunctionContext )
Script Stack: at Get-RemoteRegistrySubKey<Process>, C:\Temp\HealthChecker.ps1: line 7210
at Get-NicPnpCapabilitiesSetting<Process>, C:\Temp\HealthChecker.ps1: line 9088
at Get-NicInformation<Process>, C:\Temp\HealthChecker.ps1: line 9197
at Get-AllNicInformation<Process>, C:\Temp\HealthChecker.ps1: line 9389
at Get-OperatingSystemInformation, C:\Temp\HealthChecker.ps1: line 9892
at Get-HealthCheckerExchangeServer, C:\Temp\HealthChecker.ps1: line 10089
at Main, C:\Temp\HealthChecker.ps1: line 12229
at <ScriptBlock>, C:\Temp\HealthChecker.ps1: line 12262
at <ScriptBlock>, <No file>: line 1
at <ScriptBlock><End>, c:\users\userA\server.fqdn.psm1at.psm1: line 15761
at <ScriptBlock>, <No file>: line 1
-----------------------------------

```

**Additional context**
Problem code: 

```
        function Get-NicPnpCapabilitiesSetting {
            [CmdletBinding()]
            param(
                [ValidateNotNullOrEmpty()]
                [string]$NicAdapterComponentId
            )
            begin {
                $nicAdapterBasicPath = "SYSTEM\CurrentControlSet\Control\Class\{4D36E972-E325-11CE-BFC1-08002bE10318}"
                [int]$i = 0
                Write-Verbose "Probing started to detect NIC adapter registry path"
            }
            process {
                $registrySubKey = Get-RemoteRegistrySubKey -MachineName $ComputerName `
                    -SubKey $nicAdapterBasicPath
                $optionalKeys = $registrySubKey.GetSubKeyNames() | Where-Object { $_ -like "0*" }         # HERE IS THE PROBLEM
                do {
                    $nicAdapterPnPCapabilitiesProbingKey = "$nicAdapterBasicPath\$($optionalKeys[$i])"
                    $netCfgInstanceId = Get-RemoteRegistryValue -MachineName $ComputerName `
                        -SubKey $nicAdapterPnPCapabilitiesProbingKey `
                        -GetValue "NetCfgInstanceId" `
                        -CatchActionFunction $CatchActionFunction

                    if ($netCfgInstanceId -eq $NicAdapterComponentId) {
                        Write-Verbose "Matching ComponentId found - now checking for PnPCapabilitiesValue"
                        $nicAdapterPnPCapabilitiesValue = Get-RemoteRegistryValue -MachineName $ComputerName `
                            -SubKey $nicAdapterPnPCapabilitiesProbingKey `
                            -GetValue "PnPCapabilities" `
                            -CatchActionFunction $CatchActionFunction
                        break
                    } else {
                        Write-Verbose "No matching ComponentId found"
                        $i++
                    }
                } while ($i -lt $optionalKeys.Count)
            }
            end {
                return [PSCustomObject]@{
                    PnPCapabilities   = $nicAdapterPnPCapabilitiesValue
                    SleepyNicDisabled = ($nicAdapterPnPCapabilitiesValue -eq 24 -or $nicAdapterPnPCapabilitiesValue -eq 280)
                }
            }
        }
```

Likely need to put this into a `try` `catch` block to be able to properly handle this information.

**Comment by dpaulson45** [comment]
Haven't seen another issue on this in some time now. Going to close the issue.
