### ISSUE TITLE
"System.Management.Automation.ParameterBindingException: Cannot convert 'System.Object[]' 

### ISSUE THREAD

**Issue by dpaulson45** [microsoft/CSS-Exchange#159]
**Is your request related to a problem? Please describe.**
When trying to update the `ActiveSyncVirtualDirectory` on a server, it fails if there are 2 results on the server when running the following:

```
get-ActiveSyncVirtualDirectory -server $env:computername
```

**Describe The Request**
Call this out in the script and provide what to do.

**Additional context**
```
Error:
The following error was generated when "$error.Clear();
 $fe = get-ActiveSyncVirtualDirectory -server $RoleFqdnOrName -DomainController $RoleDomainController -ErrorAction SilentlyContinue;
 if ($fe -eq $null)
 {
 new-ActiveSyncVirtualDirectory -DomainController $RoleDomainController -Role ClientAccess;
 }
 else
 {
 update-ActiveSyncVirtualDirectory $fe -DomainController $RoleDomainController -InstallIsapiFilter $true
 }
 " was run: "System.Management.Automation.ParameterBindingException: Cannot convert 'System.Object[]' to the type 'Microsoft.Exchange.Configuration.Tasks.VirtualDirectoryIdParameter' required by parameter 'Identity'. Specified method is not supported. ---> System.NotSupportedException: Specified method is not supported.
 at System.Management.Automation.ParameterBinderBase.CoerceTypeAsNeeded(CommandParameterInternal argument, String parameterName, Type toType, ParameterCollectionTypeInformation collectionTypeInfo, Object currentValue)
 --- End of inner exception stack trace ---
 at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input, Hashtable errorResults, Boolean enumerate)
 at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput, CommandParameterInternal[][] pipeElements, CommandBaseAst[] pipeElementAsts, CommandRedirection[][] commandRedirections, FunctionContext funcContext)
 at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame)
 at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)".
```

**Comment by dpaulson45** [comment]
For this issue, we need to just do an LDAP query with the filter on `(objectCategory=msExchMobileVirtualDirectory)`. However, we need to be able to find the Server in the Configuration container to set where to search from. In my lab we are searching from here: `CN=SOLO-E19A,CN=Servers,CN=Exchange Administrative Group (FYDIBOHF23SPDLT),CN=Administrative Groups,CN=SoloORG,CN=Microsoft Exchange,CN=Services,CN=Configuration,DC=Solo,DC=com`

We are going to return 2 results if on Exchange 2016+. Then we need to filter out the Backend value by looking at the name to see if it has  `(Exchange Back End)`. If it does remove it, then if the count is great than 1 we have an issue that we need to throw.
