### ISSUE TITLE
Setup - System Mailboxes missing Last Name

### ISSUE THREAD

**Issue by dpaulson45** [microsoft/CSS-Exchange#578]
**Is your request related to a problem? Please describe.**

See this issue in the setup log

```
[05/06/2021 15:10:32.0435] [1] [ERROR] The following error was generated when "$error.Clear(); 
          $auditLogMbxName = "SystemMailbox{8cc370d3-822a-4ab8-a926-bb94bd0641a9}";
          $auditLogMbxLastName = "SystemMailbox 8cc370d3-822a-4ab8-a926-bb94bd0641a9";
          Write-ExchangeSetupLog -Info ("Retrieving users with LastName=$auditLogMbxLastName.");
          $auditLogUser = @(Get-User -Filter {LastName -eq $auditLogMbxLastName} -IgnoreDefaultScope -ResultSize 1);
          if ($auditLogUser.Length -eq 0)
          {
            Write-ExchangeSetupLog -Info ("Retrieving audit log users with LastName=$auditLogMbxLastName.");
            $auditLogUser = @(Get-User -AuditLog -Filter {LastName -eq $auditLogMbxLastName} -IgnoreDefaultScope -ResultSize 1);
          }

          if ($auditLogUser.Length -eq 0)
          {
            Write-ExchangeSetupLog -Info ("Installing user account with Name=$auditLogMbxName and LastName=$auditLogMbxLastName.");
            Install-UserAccount -Name $auditLogMbxName -LastName $auditLogMbxLastName;
          }
          else
          {
            Write-ExchangeSetupLog -Info ("Audit log user $auditLogMbxName already exists.");
          }
        " was run: "Microsoft.Exchange.Data.Directory.ADConstraintViolationException: An Active Directory Constraint Violation error occurred on ServerFQDN. Additional information: The operation failed because UPN value provided for addition/modification is not unique forest-wide.
Active directory response: 000021C8: AtrErr: DSID-03200BF6, #1:
	0: 000021C8: DSID-03200BF6, problem 1005 (CONSTRAINT_ATT_TYPE), data 0, Att 90290 (userPrincipalName)
 ---> System.DirectoryServices.Protocols.DirectoryOperationException: A value in the request is invalid.
   at System.DirectoryServices.Protocols.LdapConnection.ConstructResponse(Int32 messageId, LdapOperation operation, ResultAll resultType, TimeSpan requestTimeOut, Boolean exceptionOnTimeOut)
   at System.DirectoryServices.Protocols.LdapConnection.SendRequest(DirectoryRequest request, TimeSpan requestTimeout)
   at Microsoft.Exchange.Data.Directory.GuardedDirectoryExecution.Execute[T](String bucketName, Func`1 action, Int64& concurrency)
   at Microsoft.Exchange.Data.Directory.PooledLdapConnection.GuardedSendRequest(String forestName, GuardedDirectoryExecution guardedDirectoryExecution, DirectoryRequest request, TimeSpan timeout, Func`3 sendRequestDelegate, Int64& concurrency)
   at Microsoft.Exchange.Data.Directory.PooledLdapConnection.SendRequest(DirectoryRequest request, LdapOperation ldapOperation, Nullable`1 clientSideSearchTimeout, IADLogContext logContext, Boolean shouldLogLastFilter)
   at Microsoft.Exchange.Data.Directory.ADDataSession.ExecuteModificationRequest(ADObject entry, DirectoryRequest request, ADObjectId originalId, Boolean emptyObjectSessionOnException, Boolean isSync)
   --- End of inner exception stack trace ---
   at Microsoft.Exchange.Data.Directory.ADDataSession.AnalyzeDirectoryError(PooledLdapConnection connection, DirectoryRequest request, DirectoryException de, Int32 totalRetries, Int32 retriesOnServer, String callerFilePath, Int32 callerFileLine, String memberName)
   at Microsoft.Exchange.Data.Directory.ADDataSession.ExecuteModificationRequest(ADObject entry, DirectoryRequest request, ADObjectId originalId, Boolean emptyObjectSessionOnException, Boolean isSync)
   at Microsoft.Exchange.Data.Directory.ADDataSession.Save(ADObject instanceToSave, IEnumerable`1 properties, Boolean bypassValidation)
   at Microsoft.Exchange.Data.Directory.Recipient.ADRecipientObjectSession.Save(ADRecipient instanceToSave, String callerFilePath, Int32 callerFileLine, String memberName)
   at Microsoft.Exchange.Management.Deployment.InstallUserAccount.InternalProcessRecord()
   at Microsoft.Exchange.Configuration.Tasks.Task.<ProcessRecord>b__91_1()
   at Microsoft.Exchange.Configuration.Tasks.Task.InvokeRetryableFunc(String funcName, Action func, Boolean terminatePipelineIfFailed)".
```

**Describe The Request**

Add a check for this in the SetupAssist for the mailboxes that are causing this issue. Also add a check for this in the SetupLogReviewer. 

**Additional context**

It appears that the Last Name of the User object is null or doesn't match what we are looking for. This is why we can't find it and are trying to create a new mailbox.

**Comment by dpaulson45** [comment]
Determined that this code does work with setup when we load in the snap in vs when we are using EMS. 

Need to do an LDP query for them like Setup is doing to see if they are found, if not, check to see if the mailbox can be found with the same UPN and if it can be, throw a failure. 


Here are the code sections from a 2019 lab setup log. 

```
          if (!$RoleIsDatacenter -and !$RoleIsDatacenterDedicated)
          {
          $arbMbxname = "SystemMailbox{1f05a927-" + [System.Guid]::NewGuid().ToString().Substring(9) + "}";
          $arbMbxLastName = "MSExchApproval 1f05a927-3be2-4fb9-aa03-b59fe3b56f4c";
          $arbUser = @(Get-User -Filter {LastName -eq $arbMbxLastName} -IgnoreDefaultScope -ResultSize 1);
          if ($arbUser.Length -eq 0)
          {
          $arbUser = @(Get-User -Arbitration -Filter {LastName -eq $arbMbxLastName} -IgnoreDefaultScope -ResultSize 1);
          }

          if ($arbUser.Length -eq 0)
          {
          Install-UserAccount -Name $arbMbxname -LastName $arbMbxLastName;
          }
          }        
```


```
          $arbMbxName = "SystemMailbox{bb558c35-97f1-4cb9-8ff7-d53741dc928c}";
          $arbMbxLastName = "SystemMailbox bb558c35-97f1-4cb9-8ff7-d53741dc928c";
          Write-ExchangeSetupLog -Info ("Retrieving users with LastName=$arbMbxLastName.");
          $arbUser = @(Get-User -Filter {LastName -eq $arbMbxLastName} -IgnoreDefaultScope -ResultSize 1);
          if ($arbUser.Length -eq 0)
          {
            Write-ExchangeSetupLog -Info ("Retrieving arbitration users with LastName=$arbMbxLastName.");
            $arbUser = @(Get-User -Arbitration -Filter {LastName -eq $arbMbxLastName} -IgnoreDefaultScope -ResultSize 1);
          }

          if ($arbUser.Length -eq 0)
          {
            Write-ExchangeSetupLog -Info ("Installing user account with Name=$arbMbxName and LastName=$arbMbxLastName.");
            Install-UserAccount -Name $arbMbxName -LastName $arbMbxLastName;
          }
```


```
          $arbMbxname = "SystemMailbox{e0dc1c29-89c3-4034-b678-e6c29d823ed9}";
          $arbMbxLastName = "MsExchDiscovery e0dc1c29-89c3-4034-b678-e6c29d823ed9";
          $arbUser = @(Get-User -Filter {LastName -eq $arbMbxLastName} -IgnoreDefaultScope -ResultSize 1);
          if ($arbUser.Length -eq 0) 
          {
            $arbUser = @(Get-User -Arbitration -Filter {LastName -eq $arbMbxLastName} -IgnoreDefaultScope -ResultSize 1);
          }

          if ($arbUser.Length -eq 0)
          {
            Install-UserAccount -Name $arbMbxname -LastName $arbMbxLastName;
          }
```


```
          $arbMbxname = [Microsoft.Exchange.Management.RecipientTasks.EnableMailbox]::DiscoveryMailboxUniqueName;
          $arbMbxLastName = "MsExchDiscoveryMailbox D919BA05-46A6-415f-80AD-7E09334BB852";
          $arbUser = @(Get-User -Filter {LastName -eq $arbMbxLastName} -IgnoreDefaultScope -ResultSize 1);
        
          if ($arbUser.Length -eq 0)
          {
            Install-UserAccount -Name $arbMbxname -LastName $arbMbxLastName;
          }
```


```
            $mailboxId = [Microsoft.Exchange.Management.Migration.MigrationService.Batch.MigrationBatchIdParameter]::MigrationMailboxName;
            Write-ExchangeSetupLog -info ("about to create the mailbox user $mailboxId");
            $users = @(Get-User -Filter {LastName -eq $mailboxId} -IgnoreDefaultScope -ResultSize 1);
            if ($users.Length -eq 0)
            {
              $users = @(Get-User -Arbitration -Filter {LastName -eq $mailboxId} -IgnoreDefaultScope -ResultSize 1);
            }

            if ($users.Length -eq 0)
            {
              Install-UserAccount -Name $mailboxId -LastName $mailboxId;
            }
        
```


```
          if (!$RoleIsDatacenter)
          {
            $federatedMailboxId = [Microsoft.Exchange.Management.Deployment.UpdateRmsSharedIdentity]::SharedIdentityCommonName;
            $federatedEmailUsers = @(Get-User -Filter {LastName -eq $federatedMailboxId} -IgnoreDefaultScope -ResultSize 1);
            if ($federatedEmailUsers.Length -eq 0)
            {
              $federatedEmailUsers = @(Get-User -Arbitration -Filter {LastName -eq $federatedMailboxId} -IgnoreDefaultScope -ResultSize 1);
            }

            if ($federatedEmailUsers.Length -eq 0)
            {
              Install-UserAccount -Name $federatedMailboxId -LastName $federatedMailboxId;
            }
          }
        
```


```
            $mailboxId = "SystemMailbox{D0E409A0-AF9B-4720-92FE-AAC869B0D201}";
            Write-ExchangeSetupLog -Info ("Retrieving users with LastName=$mailboxId.");
            $arbUser = @(Get-User -Filter {LastName -eq $mailboxId} -IgnoreDefaultScope -ResultSize 1);
            if ($arbUser.Length -eq 0)
            {
                Write-ExchangeSetupLog -Info ("Retrieving arbitration users with LastName=$mailboxId.");
                $arbUser = @(Get-User -Arbitration -Filter {LastName -eq $mailboxId} -IgnoreDefaultScope -ResultSize 1);
            }

            if ($arbUser.Length -eq 0)
            {
                Write-ExchangeSetupLog -Info ("Installing user account with Name=$mailboxId and LastName=$mailboxId.");
                Install-UserAccount -Name $mailboxId -LastName $mailboxId;
            }
        
```


```
          $mailboxId = "SystemMailbox{2CE34405-31BE-455D-89D7-A7C7DA7A0DAA}";
          Write-ExchangeSetupLog -Info ("Retrieving users with LastName=$mailboxId.");
          $arbUser = @(Get-User -Filter {LastName -eq $mailboxId} -IgnoreDefaultScope -ResultSize 1);
          if ($arbUser.Length -eq 0)
          {
          Write-ExchangeSetupLog -Info ("Retrieving arbitration users with LastName=$mailboxId.");
          $arbUser = @(Get-User -Arbitration -Filter {LastName -eq $mailboxId} -IgnoreDefaultScope -ResultSize 1);
          }

          if ($arbUser.Length -eq 0)
          {
          Write-ExchangeSetupLog -Info ("Installing user account with Name=$mailboxId and LastName=$mailboxId.");
          Install-UserAccount -Name $mailboxId -LastName $mailboxId;
          }
```


```
          $auditLogMbxName = "SystemMailbox{8cc370d3-822a-4ab8-a926-bb94bd0641a9}";
          $auditLogMbxLastName = "SystemMailbox 8cc370d3-822a-4ab8-a926-bb94bd0641a9";
          Write-ExchangeSetupLog -Info ("Retrieving users with LastName=$auditLogMbxLastName.");
          $auditLogUser = @(Get-User -Filter {LastName -eq $auditLogMbxLastName} -IgnoreDefaultScope -ResultSize 1);
          if ($auditLogUser.Length -eq 0)
          {
            Write-ExchangeSetupLog -Info ("Retrieving audit log users with LastName=$auditLogMbxLastName.");
            $auditLogUser = @(Get-User -AuditLog -Filter {LastName -eq $auditLogMbxLastName} -IgnoreDefaultScope -ResultSize 1);
          }

          if ($auditLogUser.Length -eq 0)
          {
            Write-ExchangeSetupLog -Info ("Installing user account with Name=$auditLogMbxName and LastName=$auditLogMbxLastName.");
            Install-UserAccount -Name $auditLogMbxName -LastName $auditLogMbxLastName;
          }
          else
          {
            Write-ExchangeSetupLog -Info ("Audit log user $auditLogMbxName already exists.");
          }
```
