### ISSUE TITLE
[Issue] SetupAssist Test-DomainMultiActiveSyncVirtualDirectories failing on FindAll

### ISSUE THREAD

**Issue by dpaulson45** [microsoft/CSS-Exchange#871]
**Describe the issue**
The `Test-DomainMultiActiveSyncVirtualDirectories` test is failing when trying to find the object on the server. 

**Expected behavior**
Have a more graceful handle of the exception. 

Need to add an `unknown` type of `New-TestResult` and log that information. 

**Script Output**

```
[01/20/2022 06:08:27] : Failed to properly run Test-DomainMultiActiveSyncVirtualDirectories
[01/20/2022 06:08:27] : System.Management.Automation.MethodInvocationException: Exception calling "FindAll" with "0" argument(s): "There is no such object on the server.
" ---> System.DirectoryServices.DirectoryServicesCOMException: There is no such object on the server.

   at System.DirectoryServices.DirectoryEntry.Bind(Boolean throwIfFail)
   at System.DirectoryServices.DirectoryEntry.Bind()
   at System.DirectoryServices.DirectoryEntry.get_AdsObject()
   at System.DirectoryServices.DirectorySearcher.FindAll(Boolean findMoreThanOne)
   at CallSite.Target(Closure , CallSite , Object )
   --- End of inner exception stack trace ---
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at lambda_method(Closure , Object[] , StrongBox`1[] , InterpretedFrame )
```

**Comment by dpaulson45** [comment]
Duplicate of #827
