### ISSUE TITLE
[Issue] SetupAssist Failed to properly run Test-VirtualDirectoryConfiguration - null-valued expression

### ISSUE THREAD

**Issue by dpaulson45** [microsoft/CSS-Exchange#881]
**Describe the issue**
Failing to complete the SetupAssist for the Test-VirtualDirectoryConfiguration due to a null valued expression. This appears to be the problem code: 

```
                    $nodeToRemove = $appHostConfig.SelectSingleNode("/configuration/system.applicationHost/sites/site[@name = '$siteName']/application[@path = '$_']")
                    $nodeToRemove.ParentNode.RemoveChild($nodeToRemove) | Out-Null
```

It appears that `$nodeToRemove` is `null` or the `ParentNode` is. Either way, need to do a null check here. 

**Expected behavior**
Correctly finish this to provide a possible fix config to customers. 

**Script Output**

```
[02/02/2022 17:52:16] : Failed to properly run Test-VirtualDirectoryConfiguration
[02/02/2022 17:52:17] : System.Management.Automation.RuntimeException: You cannot call a method on a null-valued expression.
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
   at System.Management.Automation.ScriptBlock.InvokeWithPipeImpl(ScriptBlockClauseToInvoke clauseToInvoke, Boolean createLocalScope, Dictionary`2 functionsToDefine, List`1 variablesToDefine, ErrorHandlingBehavior errorHandlingBehavior, Object dollarUnder, Object input, Object scriptThis, Pipe outputPipe, InvocationInfo invocationInfo, Object[] args)
   at System.Management.Automation.ScriptBlock.<>c__DisplayClass57_0.<InvokeWithPipe>b__0()
   at System.Management.Automation.Runspaces.RunspaceBase.RunActionIfNoRunningPipelinesWithThreadCheck(Action action)
   at System.Management.Automation.ScriptBlock.InvokeWithPipe(Boolean useLocalScope, ErrorHandlingBehavior errorHandlingBehavior, Object dollarUnder, Object input, Object scriptThis, Pipe outputPipe, InvocationInfo invocationInfo, Boolean propagateAllExceptionsToTop, List`1 variablesToDefine, Dictionary`2 functionsToDefine, Object[] args)
   at System.Management.Automation.ScriptBlock.InvokeUsingCmdlet(Cmdlet contextCmdlet, Boolean useLocalScope, ErrorHandlingBehavior errorHandlingBehavior, Object dollarUnder, Object input, Object scriptThis, Object[] args)
   at Microsoft.PowerShell.Commands.ForEachObjectCommand.ProcessRecord()
   at System.Management.Automation.CommandProcessor.ProcessRecord()
[02/02/2022 17:52:17] : at <ScriptBlock>, C:\downloads\SetupAssist.ps1: line 1512
at Test-VirtualDirectoryConfiguration<Process>, C:\downloads\SetupAssist.ps1: line 1510
at RunAllTests, C:\downloads\SetupAssist.ps1: line 3598
at Main, C:\downloads\SetupAssist.ps1: line 3608
at <ScriptBlock>, C:\downloads\SetupAssist.ps1: line 3686
at <ScriptBlock>, <No file>: line 1
```

**Comment by dpaulson45** [comment]
having customer test out change:

```
                    $nodeToRemove = $appHostConfig.SelectSingleNode("/configuration/system.applicationHost/sites/site[@name = '$siteName']/application[@path = '$_']")

                    if ($null -ne $nodeToRemove -and
                        $null -ne $nodeToRemove.ParentNode ) {
                        $nodeToRemove.ParentNode.RemoveChild($nodeToRemove) | Out-Null
                    } else {
                        Write-Verbose "Failed to find the node to remove in the appHostConfig for site '$siteName' and path '$_'"
                    }
```
